modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/IThundxr/CreateNumismatics/issues"
license = "BY-NC-SA"

[[mods]]
modId = "numismatics"
version = "${version}"
displayName = "Create: Numismatics"
authors = "IThundxr, Violet, Pink, Slimeist"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "icon.png"

[[dependencies.numismatics]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.numismatics]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.numismatics]]
modId="create"
mandatory=true
versionRange="${create_forge_version}"
ordering="NONE"
side="BOTH"