name: Publish Release

on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: Platform
        options:
          - fabric
          - forge
          - both

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_BUILD: true
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: gradle

      - name: Validate Gradle Wrapper Integrity
        uses: gradle/wrapper-validation-action@v2

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Set Platform environment variable
        run: echo "PLATFORM=${{ inputs.platform }}" >> $GITHUB_ENV

      - name: Build & Publish
        run: ./gradlew numismaticsPublish